# Generated by Django 5.1.1 on 2024-10-09 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='page_content',
            new_name='menu_details',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='location',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_content', models.TextField(blank=True, null=True)),
                ('menu_name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.location')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_menu',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='pages.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MenuType',
        ),
    ]
