# Generated by Django 5.1.1 on 2024-11-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_menu_price_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onlocation', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnLocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('onlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.onlocation')),
            ],
        ),
    ]
