# Generated by Django 5.1.1 on 2024-11-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_onlocation_onlocationimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlocation',
            old_name='onlocation',
            new_name='event',
        ),
    ]
