# Generated by Django 5.1.1 on 2024-11-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_onlocation_onlocation_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlocation',
            old_name='event',
            new_name='onlocation',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('onlocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages.onlocation')),
            ],
        ),
    ]
