# Generated by Django 5.1.1 on 2024-11-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_event_onlocation_onlocation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlocation',
            name='slider_images',
            field=models.ManyToManyField(blank=True, related_name='on_locations', to='pages.image'),
        ),
    ]
