# Generated by Django 5.1.1 on 2024-11-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_onlocation_slider_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlocationimage',
            name='onlocation',
        ),
        migrations.AlterField(
            model_name='onlocation',
            name='slider_images',
            field=models.ManyToManyField(blank=True, related_name='on_locations', to='pages.onlocationimage'),
        ),
    ]
