# Generated by Django 5.1.1 on 2024-11-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_onlocationimage_onlocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlocation',
            name='slider_images',
        ),
        migrations.AddField(
            model_name='onlocationimage',
            name='onlocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.onlocation'),
        ),
    ]
