# Generated by Django 5.1.1 on 2024-11-19 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_onlocation_slider_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlocation',
            name='attandence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlocation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='onlocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='onlocation',
            name='event_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlocation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlocation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlocation',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
