# Generated by Django 5.1.1 on 2024-12-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
