# Generated by Django 5.1.1 on 2024-12-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_menu_menu_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_position',
            field=models.IntegerField(default=0),
        ),
    ]
